/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import clases.AI;
import clases.Admin;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Guillermo
 */
public class MainInterfaz extends javax.swing.JFrame {

    public static DefaultListModel<String> modeloListaGanadores;

    /**
     * Creates new form MainInterfaz
     */
    public MainInterfaz() {
        initComponents();
        coronaLabelAvatar.setVisible(false);
        coronaLabelSM.setVisible(false);
        empateLabel.setVisible(false);
        cancelLabel.setVisible(false);
        modeloListaGanadores = new DefaultListModel<>();
        ListaGanadores.setModel(modeloListaGanadores);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        empateLabel = new javax.swing.JLabel();
        cancelLabel = new javax.swing.JLabel();
        UniquePointsSM = new javax.swing.JLabel();
        UniquePointsAvatar = new javax.swing.JLabel();
        nombreAvatar = new javax.swing.JLabel();
        nombreSM = new javax.swing.JLabel();
        PuntosZ1 = new javax.swing.JLabel();
        PuntosSF1 = new javax.swing.JLabel();
        AIState = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        ListaGanadores = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        SliderAITimer = new javax.swing.JSlider();
        AvatarIMG = new javax.swing.JLabel();
        ShowMasIMG = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        coronaLabelAvatar = new javax.swing.JLabel();
        coronaLabelSM = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ganadoresAvatar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ganadoresSM = new javax.swing.JLabel();
        Colas1 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        ColasSM1 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        ColasSM2 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        ColasSM3 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        ColasSM4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Colas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ColasAvatar1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ColasAvatar2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ColasAvatar3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ColasAvatar4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empateLabel.setForeground(new java.awt.Color(255, 255, 255));
        empateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empateLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Empate.png"))); // NOI18N
        jPanel4.add(empateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 130, 190));

        cancelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cancel.png"))); // NOI18N
        jPanel4.add(cancelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 350, 120));

        UniquePointsSM.setBackground(new java.awt.Color(255, 255, 255));
        UniquePointsSM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UniquePointsSM.setForeground(new java.awt.Color(255, 255, 255));
        UniquePointsSM.setText("0");
        jPanel4.add(UniquePointsSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 50, 30));

        UniquePointsAvatar.setBackground(new java.awt.Color(255, 255, 255));
        UniquePointsAvatar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UniquePointsAvatar.setForeground(new java.awt.Color(255, 255, 255));
        UniquePointsAvatar.setText("0");
        jPanel4.add(UniquePointsAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 50, 30));

        nombreAvatar.setBackground(new java.awt.Color(255, 255, 255));
        nombreAvatar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreAvatar.setForeground(new java.awt.Color(255, 255, 255));
        nombreAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreAvatar.setText("Nombre");
        jPanel4.add(nombreAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, 30));

        nombreSM.setBackground(new java.awt.Color(255, 255, 255));
        nombreSM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreSM.setForeground(new java.awt.Color(255, 255, 255));
        nombreSM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreSM.setText("Nombre");
        jPanel4.add(nombreSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 170, 30));

        PuntosZ1.setBackground(new java.awt.Color(255, 255, 255));
        PuntosZ1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PuntosZ1.setForeground(new java.awt.Color(255, 255, 255));
        PuntosZ1.setText("Puntos:");
        jPanel4.add(PuntosZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 60, 30));

        PuntosSF1.setBackground(new java.awt.Color(255, 255, 255));
        PuntosSF1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PuntosSF1.setForeground(new java.awt.Color(255, 255, 255));
        PuntosSF1.setText("Puntos:");
        jPanel4.add(PuntosSF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 70, 30));

        AIState.setBackground(new java.awt.Color(255, 255, 255));
        AIState.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AIState.setForeground(new java.awt.Color(255, 255, 255));
        AIState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AIState.setText("CREANDO COLAS");
        jPanel4.add(AIState, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 150, 40));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Timer (seg)");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        jScrollPane13.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ListaGanadores.setBackground(new java.awt.Color(0, 0, 0));
        ListaGanadores.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ListaGanadores.setForeground(new java.awt.Color(255, 255, 255));
        ListaGanadores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ganador 1", "Ganador 2", "Ganador 3", "Ganador 4", "Ganadro 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane13.setViewportView(ListaGanadores);

        jPanel4.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 240, 50));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("GANADORES =");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        SliderAITimer.setBackground(new java.awt.Color(0, 0, 0));
        SliderAITimer.setForeground(new java.awt.Color(255, 0, 0));
        SliderAITimer.setMajorTickSpacing(1);
        SliderAITimer.setMaximum(10);
        SliderAITimer.setMinimum(1);
        SliderAITimer.setPaintLabels(true);
        SliderAITimer.setPaintTicks(true);
        SliderAITimer.setSnapToTicks(true);
        SliderAITimer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SliderAITimer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderAITimerStateChanged(evt);
            }
        });
        jPanel4.add(SliderAITimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 310, 50));

        AvatarIMG.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        AvatarIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/question.jpg"))); // NOI18N
        jPanel4.add(AvatarIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, 110));

        ShowMasIMG.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ShowMasIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/question.jpg"))); // NOI18N
        jPanel4.add(ShowMasIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 110, 110));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VS.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 70, 90));

        coronaLabelAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coronaLabelAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crown.png"))); // NOI18N
        jPanel4.add(coronaLabelAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 70, 50));

        coronaLabelSM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coronaLabelSM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crown.png"))); // NOI18N
        jPanel4.add(coronaLabelSM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 70, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 420, 430));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        ganadoresAvatar.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        ganadoresAvatar.setForeground(new java.awt.Color(255, 255, 255));
        ganadoresAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ganadoresAvatar.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ganadoresAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ganadoresAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 90, 70));

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));

        ganadoresSM.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        ganadoresSM.setForeground(new java.awt.Color(255, 255, 255));
        ganadoresSM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ganadoresSM.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ganadoresSM, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(ganadoresSM, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 90, 70));

        Colas1.setBackground(new java.awt.Color(0, 51, 255));
        Colas1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ColasSM1.setBackground(new java.awt.Color(0, 0, 255));
        ColasSM1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jScrollPane9.setViewportView(ColasSM1);

        Colas1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 240, 50));

        ColasSM2.setBackground(new java.awt.Color(0, 0, 255));
        ColasSM2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jScrollPane10.setViewportView(ColasSM2);

        Colas1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 240, 50));

        ColasSM3.setBackground(new java.awt.Color(0, 0, 255));
        ColasSM3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jScrollPane11.setViewportView(ColasSM3);

        Colas1.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 240, 50));

        ColasSM4.setBackground(new java.awt.Color(0, 0, 255));
        ColasSM4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jScrollPane12.setViewportView(ColasSM4);

        Colas1.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 240, 50));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Colas de prioridad");
        Colas1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 40));

        jPanel1.add(Colas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 270, 350));

        Colas.setBackground(new java.awt.Color(255, 153, 0));
        Colas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ColasAvatar1.setBackground(new java.awt.Color(0, 0, 255));
        ColasAvatar1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jScrollPane1.setViewportView(ColasAvatar1);

        Colas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 240, 50));

        ColasAvatar2.setBackground(new java.awt.Color(0, 0, 255));
        ColasAvatar2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jScrollPane3.setViewportView(ColasAvatar2);

        Colas.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 240, 50));

        ColasAvatar3.setBackground(new java.awt.Color(0, 0, 255));
        ColasAvatar3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jScrollPane4.setViewportView(ColasAvatar3);

        Colas.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 240, 50));

        ColasAvatar4.setBackground(new java.awt.Color(0, 0, 255));
        ColasAvatar4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jScrollPane5.setViewportView(ColasAvatar4);

        Colas.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 240, 50));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Colas de prioridad");
        Colas.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 40));

        jPanel1.add(Colas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 270, 350));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FIGHT!");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 140, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Avatar: La leyenda de Aang");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 320, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Un Show Más");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/unshowmasFondo_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 520, 630));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/avatarFondo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SliderAITimerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderAITimerStateChanged
        AI.time = SliderAITimer.getValue();
    }//GEN-LAST:event_SliderAITimerStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterfaz().setVisible(true);
            }
        });

        // Crear instancias de las clases
        Admin admin = new Admin();
        AI ai = new AI();

        // Inicializar personajes y colocarlos en las colas
        admin.initializeCharacters();

        // Simular rondas AI
        for (int round = 1; round <= 1000; round++) {
            System.out.println("\n =====RONDA " + round + "=====");

            // Mostrar las colas antes de la ronda
            admin.printQueues();

            // Seleccionar personajes para el combate desde las colas
            clases.Character[] charactersForBattle = admin.selectCharactersForBattle();
            clases.Character avatarCharacter = charactersForBattle[0];
            clases.Character showMasCharacter = charactersForBattle[1];

            if (avatarCharacter != null & showMasCharacter != null) {
                System.out.println("Pelea: " + avatarCharacter.getName() + " vs " + showMasCharacter.getName());
            }

            // Mostrar las colas en la interfaz
            admin.actualizarColasEnInterfaz();

            // Comenzar la batalla con la AI
            ai.processBattle(avatarCharacter, showMasCharacter);
        }

        System.out.println("\n === Colas finales ===");
        admin.printQueues();
        admin.actualizarColasEnInterfaz();
    }

    public static void setDefStats() {
        if (AvatarIMG != null && ShowMasIMG != null) {
            AvatarIMG.setIcon(new ImageIcon("src\\imagenes\\question.jpg"));
            ShowMasIMG.setIcon(new ImageIcon("src\\imagenes\\question.jpg"));
            nombreAvatar.setText("Buscando oponente");
            nombreSM.setText("Buscando oponente");
            UniquePointsAvatar.setText("0");
            UniquePointsSM.setText("0");

        } else {
            System.out.println("AvatarIMG o ShowMasIMG es null. Asegúrate de que estén inicializados correctamente.");
        }
    }

    public static void setZeldaIcon(String name, int power) {
        AvatarIMG.setIcon(new ImageIcon("src\\imagenes\\" + name + ".jpg"));
        nombreAvatar.setText(name);
        UniquePointsAvatar.setText(Integer.toString(power));
    }

    public static void setSFIcon(String name, int power) {
        ShowMasIMG.setIcon(new ImageIcon("src\\imagenes\\" + name + ".jpg"));
        nombreSM.setText(name);
        UniquePointsSM.setText(Integer.toString(power));
    }

    public static void marcadorZelda(int puntaje) {
        ganadoresAvatar.setText(Integer.toString(puntaje));
    }

    public static void marcadorSF(int puntaje) {
        ganadoresSM.setText(Integer.toString(puntaje));
    }

    public static JLabel getGanadoresSM() {
        return ganadoresSM;
    }

    public static void setGanadoresSM(JLabel ganadoresSM) {
        MainInterfaz.ganadoresSM = ganadoresSM;
    }

    public static JLabel getGanadoresAvatar() {
        return ganadoresAvatar;
    }

    public static void setGanadoresAvatar(JLabel ganadoresAvatar) {
        MainInterfaz.ganadoresAvatar = ganadoresAvatar;
    }

    // Método para colocar la corona sobre la imagen del personaje ganador
    public static void setCoronaPositionAvatar(JLabel characterImage) {
        coronaLabelAvatar.setVisible(true);
    }

    public static void setCoronaPositionSM(JLabel characterImage) {
        coronaLabelSM.setVisible(true);
    }

    public static void setEmpateVisible() {
        empateLabel.setVisible(true);
    }

    public static void setCancelVisible() {
        cancelLabel.setVisible(true);
    }

    public static JLabel getCancelLabel() {
        return cancelLabel;
    }

    public static void setCancelLabel(JLabel cancelLabel) {
        MainInterfaz.cancelLabel = cancelLabel;
    }

    public static JLabel getEmpateLabel() {
        return empateLabel;
    }

    public static void setEmpateLabel(JLabel empateLabel) {
        MainInterfaz.empateLabel = empateLabel;
    }

    public static void setNombreAvatar(String name) {
        nombreAvatar.setText(name);
    }

    public static void setNombreSM(String name) {
        nombreSM.setText(name);
    }

    public static JLabel getColasZelda(int index) {
        switch (index) {
            case 1:
                return ColasAvatar1;
            case 2:
                return ColasAvatar2;
            case 3:
                return ColasAvatar3;
            case 4:
                return ColasAvatar4;
            default:
                return null;
        }
    }

    public static JLabel getColasSF(int index) {
        switch (index) {
            case 1:
                return ColasSM1;
            case 2:
                return ColasSM2;
            case 3:
                return ColasSM3;
            case 4:
                return ColasSM4;
            default:
                return null;
        }
    }

    public static JLabel getAvatarIMG() {
        return AvatarIMG;
    }

    public static void setAvatarIMG(JLabel AvatarIMG) {
        MainInterfaz.AvatarIMG = AvatarIMG;
    }

    public static JLabel getShowMasIMG() {
        return ShowMasIMG;
    }

    public static void setShowMasIMG(JLabel ShowMasIMG) {
        MainInterfaz.ShowMasIMG = ShowMasIMG;
    }

    public static JLabel getUniquePointsAvatar() {
        return UniquePointsAvatar;
    }

    public static void setUniquePointsAvatar(JLabel UniquePointsAvatar) {
        MainInterfaz.UniquePointsAvatar = UniquePointsAvatar;
    }

    public static JLabel getUniquePointsSM() {
        return UniquePointsSM;
    }

    public static void setUniquePointsSM(JLabel UniquePointsSM) {
        MainInterfaz.UniquePointsSM = UniquePointsSM;
    }

    public static JLabel getNombreAvatar() {
        return nombreAvatar;
    }

    public static void setNombreAvatar(JLabel nombreAvatar) {
        MainInterfaz.nombreAvatar = nombreAvatar;
    }

    public static JLabel getNombreSM() {
        return nombreSM;
    }

    public static void setNombreSM(JLabel nombreSM) {
        MainInterfaz.nombreSM = nombreSM;
    }

    public static JLabel getColasAvatar1() {
        return ColasAvatar1;
    }

    public static void setColasAvatar1(JLabel ColasAvatar1) {
        MainInterfaz.ColasAvatar1 = ColasAvatar1;
    }

    public static JLabel getColasAvatar2() {
        return ColasAvatar2;
    }

    public static void setColasAvatar2(JLabel ColasAvatar2) {
        MainInterfaz.ColasAvatar2 = ColasAvatar2;
    }

    public static JLabel getColasAvatar3() {
        return ColasAvatar3;
    }

    public static void setColasAvatar3(JLabel ColasAvatar3) {
        MainInterfaz.ColasAvatar3 = ColasAvatar3;
    }

    public static JLabel getColasAvatar4() {
        return ColasAvatar4;
    }

    public static void setColasAvatar4(JLabel ColasAvatar4) {
        MainInterfaz.ColasAvatar4 = ColasAvatar4;
    }

    public static JLabel getColasSM1() {
        return ColasSM1;
    }

    public static void setColasSM1(JLabel ColasSM1) {
        MainInterfaz.ColasSM1 = ColasSM1;
    }

    public static JLabel getColasSM2() {
        return ColasSM2;
    }

    public static void setColasSM2(JLabel ColasSM2) {
        MainInterfaz.ColasSM2 = ColasSM2;
    }

    public static JLabel getColasSM3() {
        return ColasSM3;
    }

    public static void setColasSM3(JLabel ColasSM3) {
        MainInterfaz.ColasSM3 = ColasSM3;
    }

    public static JLabel getColasSM4() {
        return ColasSM4;
    }

    public static void setColasSM4(JLabel ColasSM4) {
        MainInterfaz.ColasSM4 = ColasSM4;
    }

    public static void agregarGanador(String elemento) {
        modeloListaGanadores.addElement(elemento);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel AIState;
    public static javax.swing.JLabel AvatarIMG;
    private javax.swing.JPanel Colas;
    private javax.swing.JPanel Colas1;
    public static javax.swing.JLabel ColasAvatar1;
    public static javax.swing.JLabel ColasAvatar2;
    public static javax.swing.JLabel ColasAvatar3;
    public static javax.swing.JLabel ColasAvatar4;
    public static javax.swing.JLabel ColasSM1;
    public static javax.swing.JLabel ColasSM2;
    public static javax.swing.JLabel ColasSM3;
    public static javax.swing.JLabel ColasSM4;
    public static javax.swing.JList<String> ListaGanadores;
    public static javax.swing.JLabel PuntosSF1;
    public static javax.swing.JLabel PuntosZ1;
    public static javax.swing.JLabel ShowMasIMG;
    private javax.swing.JSlider SliderAITimer;
    public static javax.swing.JLabel UniquePointsAvatar;
    public static javax.swing.JLabel UniquePointsSM;
    public static javax.swing.JLabel cancelLabel;
    public static javax.swing.JLabel coronaLabelAvatar;
    public static javax.swing.JLabel coronaLabelSM;
    public static javax.swing.JLabel empateLabel;
    public static javax.swing.JLabel ganadoresAvatar;
    public static javax.swing.JLabel ganadoresSM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane9;
    public static javax.swing.JLabel nombreAvatar;
    public static javax.swing.JLabel nombreSM;
    // End of variables declaration//GEN-END:variables
}
